package gitworktree

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The class a path is given decides where the patch presents it, so the rules
// are held to by name: Go's own conventions first, then the ones the projects
// here have actually shipped.
func TestClassifyPathReadsTheConventions(t *testing.T) {
	t.Parallel()

	for path, want := range map[string]FileClass{
		"internal/readmodel/throughput.go":                     FileClassSource,
		"docs/operations.md":                                   FileClassSource,
		"internal/dashboard/assets/dashboard.js":               FileClassSource,
		"cmd/yoyo/main.go":                                     FileClassSource,
		"internal/readmodel/throughput_test.go":                FileClassTest,
		"internal/dashboard/page_test.go":                      FileClassTest,
		"web/app.test.js":                                      FileClassTest,
		"web/app.spec.ts":                                      FileClassTest,
		"test/integration/smoke.go":                            FileClassTest,
		"internal/dashboard/testdata/renders/busy.html":        FileClassFixture,
		"internal/dashboard/testdata/render.js":                FileClassFixture,
		"internal/orchestrator/testdata/baseline/a-run.json":   FileClassFixture,
		"web/__snapshots__/app.test.js.snap":                   FileClassFixture,
		"spec/fixtures/users.yml":                              FileClassFixture,
		"internal/cli/golden/status.txt":                       FileClassFixture,
		"internal/cli/status.golden":                           FileClassFixture,
		"go.sum":                                               FileClassFixture,
		"web/package-lock.json":                                FileClassFixture,
		"internal/api/service.pb.go":                           FileClassFixture,
		"internal/api/zz_generated.deepcopy.go":                FileClassFixture,
		"internal/schema/types_gen.go":                         FileClassFixture,
		"internal/dashboard/testdata/fixtures/standing.json":   FileClassFixture,
		"internal/gitworktree/testdata/a_test.go":              FileClassFixture,
		"internal/gitworktree/presentation_test.go":            FileClassTest,
		"internal/backend/conformance/adapters_test.go":        FileClassTest,
		"internal/backend/conformance/suite.go":                FileClassSource,
		"docs/diagnoses/yoyodyne-ifd-238-probe-crosstalk.md":   FileClassSource,
		"internal/dashboard/testdata/renders/wrong-token.html": FileClassFixture,
	} {
		if got := ClassifyPath(path); got != want {
			t.Errorf("ClassifyPath(%q) = %q, want %q", path, got, want)
		}
	}
}

// A generated file announces itself in its own first line and nowhere in its
// path, so the marker in its rendered diff is what classes it — and only for a
// file the path calls source, since the path has already settled the others.
func TestClassifySectionReadsTheGeneratedMarker(t *testing.T) {
	t.Parallel()

	generated := "diff --git a/internal/api/types.go b/internal/api/types.go\n+// Code generated by protoc-gen-go. DO NOT EDIT.\n+package api\n"
	if got := classifySection("internal/api/types.go", generated); got != FileClassFixture {
		t.Errorf("a file carrying Go's generated marker classed as %q, want a fixture", got)
	}
	context := "diff --git a/internal/api/types.go b/internal/api/types.go\n // Code generated by mockery v2. DO NOT EDIT.\n+func added() {}\n"
	if got := classifySection("internal/api/types.go", context); got != FileClassFixture {
		t.Errorf("a modified generated file classed as %q, want a fixture", got)
	}
	shell := "diff --git a/scripts/env.sh b/scripts/env.sh\n+# Code generated by make env. DO NOT EDIT.\n"
	if got := classifySection("scripts/env.sh", shell); got != FileClassFixture {
		t.Errorf("a generated shell file classed as %q, want a fixture", got)
	}
	// The sentence quoted inside a source file's body is not the marker: the
	// marker is a whole line, and a diff line carrying prose about it is not one.
	prose := "diff --git a/internal/gitworktree/manager.go b/internal/gitworktree/manager.go\n+\t// A generated file carries `// Code generated ... DO NOT EDIT.` at its head.\n"
	if got := classifySection("internal/gitworktree/manager.go", prose); got != FileClassSource {
		t.Errorf("prose about the marker classed the file as %q, want source", got)
	}
	// A line removed from the file is the file's past, not its present.
	removed := "diff --git a/internal/api/types.go b/internal/api/types.go\n-// Code generated by protoc-gen-go. DO NOT EDIT.\n+package api\n"
	if got := classifySection("internal/api/types.go", removed); got != FileClassSource {
		t.Errorf("a removed marker classed the file as %q, want source", got)
	}
}

// The bound is spent source first, then tests, then test data, across the
// committed and uncommitted halves of a worktree together, so a change whose
// fixtures sort ahead of its code presents the code whole and lets the bound
// fall on the fixtures. Git lists both halves alphabetically, which is the order
// that sent yoyodyne-ifd.141.3's read model to review unseen.
func TestManagerUnifiedChangesPresentsSourceThenTestsThenFixtures(t *testing.T) {
	t.Parallel()

	repository := newRepository(t)
	manager := newManager(t, repository, filepath.Join(t.TempDir(), "worktrees"))
	worktree, err := manager.Create(context.Background(), CreateRequest{RunID: testRunID, WorkItemID: "yoyodyne-order", BaseRef: "HEAD"})
	if err != nil {
		t.Fatalf("Create() error = %v", err)
	}
	// Alphabetically the renders come first and the read model last, and the
	// generated file sorts among the source. One source file and one test are
	// committed by an earlier attempt; the others are this round's worktree.
	writeFile(t, worktree.Path, "internal/dashboard/testdata/renders/busy.html", strings.Repeat("<li>a rendered row</li>\n", 10))
	writeFile(t, worktree.Path, "internal/dashboard/testdata/renders/quiet.html", strings.Repeat("<li>a quiet row</li>\n", 10))
	writeFile(t, worktree.Path, "internal/readmodel/standing.go", "package readmodel\n\nfunc Standing() {}\n")
	writeFile(t, worktree.Path, "internal/readmodel/standing_test.go", "package readmodel\n\nfunc TestStanding() {}\n")
	worktree.HarnessCommit = harnessCommit(t, worktree.Path, "yoyodyne: published attempt")
	writeFile(t, worktree.Path, "internal/api/types.go", "// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage api\n")
	writeFile(t, worktree.Path, "internal/readmodel/throughput.go", "package readmodel\n\nfunc Throughput() {}\n")
	writeFile(t, worktree.Path, "internal/readmodel/throughput_test.go", "package readmodel\n\nfunc TestThroughput() {}\n")

	whole, err := manager.UnifiedChanges(context.Background(), worktree, DiffLimits{})
	if err != nil {
		t.Fatalf("UnifiedChanges() error = %v", err)
	}
	if whole.Truncated {
		t.Fatalf("an unbounded change was reported as cut: %#v", whole.OmittedFiles)
	}
	order := []string{
		"internal/readmodel/standing.go",
		"internal/readmodel/throughput.go",
		"internal/readmodel/standing_test.go",
		"internal/readmodel/throughput_test.go",
		"internal/api/types.go",
		"internal/dashboard/testdata/renders/busy.html",
		"internal/dashboard/testdata/renders/quiet.html",
	}
	assertPatchOrder(t, whole.Patch, order)
	// The listing says what each file is, in the order Git gave it: the listing
	// is the inventory and the patch is the presentation.
	classes := map[string]FileClass{}
	for _, file := range whole.Files {
		classes[file.Path] = file.Class
	}
	for path, want := range map[string]FileClass{
		"internal/readmodel/throughput.go":              FileClassSource,
		"internal/readmodel/throughput_test.go":         FileClassTest,
		"internal/dashboard/testdata/renders/busy.html": FileClassFixture,
	} {
		if classes[path] != want {
			t.Errorf("listing classes %s as %q, want %q", path, classes[path], want)
		}
	}
	if described := (ChangedFile{Path: "internal/dashboard/testdata/renders/busy.html", Status: "A", Bytes: 240, Class: FileClassFixture}).Describe(); !strings.Contains(described, "test data or generated") {
		t.Errorf("a listed fixture is not said to be one: %q", described)
	}

	// A bound that holds the source and the tests and not the renders. The
	// generated file is a fixture too, so it is behind the tests whatever its
	// path sorts as, and the bound falls on it and on the renders.
	sourceAndTests := 0
	for _, path := range order[:4] {
		sourceAndTests += len(sectionFor(t, whole.Patch, path))
	}
	bounded, err := manager.UnifiedChanges(context.Background(), worktree, DiffLimits{MaxTotalBytes: sourceAndTests + 40})
	if err != nil {
		t.Fatalf("UnifiedChanges() bounded error = %v", err)
	}
	if !bounded.Truncated {
		t.Fatalf("a bounded change was reported as complete: %#v", bounded)
	}
	assertPatchOrder(t, bounded.Patch, order[:4])
	for _, kept := range order[:4] {
		if !strings.Contains(bounded.Patch, "diff --git a/"+kept+" b/"+kept) {
			t.Errorf("a file ahead of the bound is missing from the patch: %s\n%s", kept, bounded.Patch)
		}
	}
	for _, dropped := range order[4:] {
		if strings.Contains(bounded.Patch, dropped) {
			t.Errorf("a fixture behind the bound is in the patch: %s", dropped)
		}
	}
	// What was cut is the tail of the order, named in that order, and each one
	// says it is a fixture — a reviewer told the patch is missing test data
	// reads the omission differently from one told it is missing code.
	if len(bounded.OmittedFiles) != 3 {
		t.Fatalf("omitted files = %#v, want the three fixtures", bounded.OmittedFiles)
	}
	for index, dropped := range order[4:] {
		omitted := bounded.OmittedFiles[index]
		if omitted.Path != dropped || omitted.Class != FileClassFixture || omitted.Reason != OmittedPatchFull {
			t.Errorf("omission %d = %#v, want %s named as a fixture the bound had no room for", index, omitted, dropped)
		}
		if described := omitted.Describe(); !strings.Contains(described, "test data or generated") || !strings.Contains(described, dropped) {
			t.Errorf("described omission = %q, want the path and its class", described)
		}
	}
	// A source omission is described without a class: code is what a reviewer
	// assumes an omission is, and saying so would say nothing.
	if described := (OmittedFile{Path: "big.go", Bytes: 10, Reason: OmittedPatchFull, Class: FileClassSource, Bound: 5}).Describe(); strings.Contains(described, "source") {
		t.Errorf("a source omission names its class: %q", described)
	}
}

// The accumulated change on a branch is presented in the same order, for the
// same reason: the reviewer must not have to care which of the two it was
// handed.
func TestBranchChangesPresentsSourceThenTestsThenFixtures(t *testing.T) {
	t.Parallel()

	repository := newRepository(t)
	accumulate(t, repository, "accumulated",
		[2]string{"internal/dashboard/testdata/renders/busy.html", strings.Repeat("<li>a rendered row</li>\n", 10)},
		[2]string{"internal/readmodel/throughput.go", "package readmodel\n\nfunc Throughput() {}\n"},
		[2]string{"internal/readmodel/throughput_test.go", "package readmodel\n\nfunc TestThroughput() {}\n"},
	)
	manager := newManager(t, repository, filepath.Join(t.TempDir(), "worktrees"))

	whole, err := manager.BranchChanges(context.Background(), BranchRequest{Branch: "accumulated", BaseRef: "main"}, DiffLimits{})
	if err != nil {
		t.Fatalf("BranchChanges() error = %v", err)
	}
	order := []string{"internal/readmodel/throughput.go", "internal/readmodel/throughput_test.go", "internal/dashboard/testdata/renders/busy.html"}
	assertPatchOrder(t, whole.Changes.Patch, order)

	codeBytes := len(sectionFor(t, whole.Changes.Patch, order[0])) + len(sectionFor(t, whole.Changes.Patch, order[1]))
	bounded, err := manager.BranchChanges(context.Background(), BranchRequest{Branch: "accumulated", BaseRef: "main"}, DiffLimits{MaxTotalBytes: codeBytes + 40})
	if err != nil {
		t.Fatalf("BranchChanges() bounded error = %v", err)
	}
	assertPatchOrder(t, bounded.Changes.Patch, order[:2])
	if strings.Contains(bounded.Changes.Patch, "busy.html") {
		t.Errorf("the fixture behind the bound is in the patch:\n%s", bounded.Changes.Patch)
	}
	if len(bounded.Changes.OmittedFiles) != 1 || bounded.Changes.OmittedFiles[0].Path != order[2] ||
		bounded.Changes.OmittedFiles[0].Class != FileClassFixture || bounded.Changes.OmittedFiles[0].Reason != OmittedPatchFull {
		t.Fatalf("omitted files = %#v, want the render named as a fixture the bound had no room for", bounded.Changes.OmittedFiles)
	}
}

// yoyodyne-ifd.141.3's change replayed through the default bound: the shape of
// its diff against its base — every path, with the size of that path's diff —
// is what went to review, 368,503 bytes against a 262,144-byte bound. Spent
// alphabetically, the bound was gone before internal/readmodel was reached and
// the read model went to review unseen; spent in class order, the read model
// and every other source and test file is presented whole and what the bound
// keeps out is renders.
func TestTheDashboardPageChangeReplayedThroughTheBoundPresentsTheReadModelWhole(t *testing.T) {
	t.Parallel()

	repository := newRepository(t)
	manager := newManager(t, repository, filepath.Join(t.TempDir(), "worktrees"))
	worktree, err := manager.Create(context.Background(), CreateRequest{RunID: testRunID, WorkItemID: "yoyodyne-ifd.141.3", BaseRef: "HEAD"})
	if err != nil {
		t.Fatalf("Create() error = %v", err)
	}
	// Each file is written at the byte size of its diff in the real change, as
	// lines, so the rendered diff here is that size plus a header and a `+` a
	// line: within a few percent of what the reviewer was handed.
	for path, bytes := range dashboardPageDiffShape {
		lines := bytes / 40
		writeFile(t, worktree.Path, path, strings.Repeat(strings.Repeat("x", 39)+"\n", lines))
	}
	worktree.HarnessCommit = harnessCommit(t, worktree.Path, "yoyodyne: yoyodyne-ifd.141.3 Dashboard 3 of 3")

	changes, err := manager.UnifiedChanges(context.Background(), worktree, DiffLimits{})
	if err != nil {
		t.Fatalf("UnifiedChanges() error = %v", err)
	}
	if !changes.Truncated {
		t.Fatalf("a change of %d bytes against a %d-byte bound was reported as complete", len(changes.Patch), DefaultMaxDiffBytes)
	}
	if len(changes.Patch) > DefaultMaxDiffBytes {
		t.Fatalf("patch is %d bytes, want at most %d", len(changes.Patch), DefaultMaxDiffBytes)
	}
	for path := range dashboardPageDiffShape {
		class := ClassifyPath(path)
		shown := strings.Contains(changes.Patch, "diff --git a/"+path+" b/"+path)
		if class != FileClassFixture && !shown {
			t.Errorf("%s (%s) is not in the patch; the bound cut code ahead of the fixtures", path, class)
		}
	}
	for _, omitted := range changes.OmittedFiles {
		if omitted.Class != FileClassFixture || !strings.HasPrefix(omitted.Path, "internal/dashboard/testdata/") {
			t.Errorf("the bound kept out %s (%s); only renders and fixtures may be behind it", omitted.Path, omitted.Class)
		}
	}
	if len(changes.OmittedFiles) == 0 {
		t.Fatal("nothing was kept out of a change larger than the bound")
	}
	// The read model in particular — the throughput derivation the page depends
	// on, which is what the reviewer said she had not seen — is whole.
	for _, path := range []string{
		"internal/readmodel/standing.go", "internal/readmodel/throughput.go",
		"internal/readmodel/standing_test.go", "internal/readmodel/throughput_test.go",
	} {
		section := sectionFor(t, changes.Patch, path)
		line := "+" + strings.Repeat("x", 39) + "\n"
		if want := dashboardPageDiffShape[path] / 40; strings.Count(section, line) != want {
			t.Errorf("%s is shown with %d of its %d lines", path, strings.Count(section, line), want)
		}
	}

	// And the change is one a reviewer can approve. Ordering the bound put the
	// code in front of her; this is the other half of it — every omission is a
	// fixture, and every one of those is listed with the size and the digest that
	// make it openable, so nothing about the representation refuses the approval.
	// Without it the change is reviewable and unclosable, which is what
	// yoyodyne-ifd.404 left behind and what yoyodyne-ifd.425 is for.
	if problems := changes.UnreviewableOmissions(); len(problems) > 0 {
		t.Errorf("the change cannot be approved: %s", strings.Join(problems, "; "))
	}
	for _, omitted := range changes.OmittedFiles {
		if !strings.HasPrefix(omitted.Digest, "sha256:") || !omitted.ListedWhole() {
			t.Errorf("omission = %#v, want it delivered as evidence somebody can open and check", omitted)
		}
	}
}

// A fixture the change delivers as a symlink is not a fixture anybody can open,
// and it refuses the approval whether Git tracks it or not. Tracked is the case
// worth a test of its own: the worktree holds no regular file there, so the
// omission measures zero bytes and digests to nothing exactly as a deletion
// does, and it keeps the reason of whichever bound dropped it rather than being
// renamed unreadable — that reason is still true of it. Told apart from a
// deletion only by the flag, and read as one without it, it would have been a
// whole listing and let the approval past.
func TestATrackedSymlinkFixtureIsNotReadAsADeletedOne(t *testing.T) {
	t.Parallel()

	repository := newRepository(t)
	manager := newManager(t, repository, filepath.Join(t.TempDir(), "worktrees"))
	worktree, err := manager.Create(context.Background(), CreateRequest{RunID: testRunID, WorkItemID: "yoyodyne-link", BaseRef: "HEAD"})
	if err != nil {
		t.Fatalf("Create() error = %v", err)
	}
	writeFile(t, worktree.Path, "internal/readmodel/standing.go", strings.Repeat("// the read model this page depends on\n", 40))
	writeFile(t, worktree.Path, "internal/dashboard/testdata/renders/busy.html", strings.Repeat("<li>a rendered row</li>\n", 40))
	if err := os.Symlink("busy.html", filepath.Join(worktree.Path, "internal/dashboard/testdata/renders/latest.html")); err != nil {
		t.Fatalf("Symlink() error = %v", err)
	}
	worktree.HarnessCommit = harnessCommit(t, worktree.Path, "yoyodyne: published attempt")

	// A bound the source spends and the fixtures cannot fit inside, so the link
	// is reached with the patch already full.
	changes, err := manager.UnifiedChanges(context.Background(), worktree, DiffLimits{MaxTotalBytes: 1800})
	if err != nil {
		t.Fatalf("UnifiedChanges() error = %v", err)
	}
	omitted := map[string]OmittedFile{}
	for _, file := range changes.OmittedFiles {
		omitted[file.Path] = file
	}
	link, ok := omitted["internal/dashboard/testdata/renders/latest.html"]
	if !ok {
		t.Fatalf("omitted files = %#v, want the link among them", changes.OmittedFiles)
	}
	if !link.Undigestable || link.Digest != "" || link.Bytes != 0 || link.ListedWhole() {
		t.Errorf("tracked link omission = %#v, want nothing to open and a listing that is not whole", link)
	}
	// The reason still says which bound dropped it, which is what a deletion
	// dropped by the same bound would say — the flag is the whole difference.
	if link.Reason == OmittedUnreadable {
		t.Errorf("tracked link omission = %#v, want the bound that dropped it rather than a claim there was nothing to diff", link)
	}
	if described := link.Describe(); !strings.Contains(described, "nothing to open") {
		t.Errorf("described omission = %q, want it to say why there is no digest", described)
	}
	// And it is what stops the approval, where the regular fixture beside it is
	// listed whole and stops nothing.
	if render := omitted["internal/dashboard/testdata/renders/busy.html"]; !strings.HasPrefix(render.Digest, "sha256:") || !render.ListedWhole() {
		t.Errorf("regular fixture omission = %#v, want it listed whole with a digest", render)
	}
	problems := changes.UnreviewableOmissions()
	if len(problems) != 1 || !strings.Contains(problems[0], "latest.html") {
		t.Fatalf("unreviewable = %#v, want the link named as the one omission no approval covers", problems)
	}
}

// The narrowed refusal, at the grain the rule is written in: an omission is one
// a review can be completed over only where it is test data and the listing says
// which bytes were kept out.
func TestUnreviewableOmissionsNamesWhatAnApprovalCannotCover(t *testing.T) {
	t.Parallel()

	listed := OmittedFile{
		Path: "internal/dashboard/testdata/renders/busy.html", Bytes: 21873, Reason: OmittedPatchFull,
		Class: FileClassFixture, Bound: 262144, Digest: "sha256:" + strings.Repeat("a", 64),
	}
	deleted := OmittedFile{
		Path: "internal/dashboard/testdata/renders/gone.html", Bytes: 0, Reason: OmittedPatchFull,
		Class: FileClassFixture, Bound: 262144, DiffBytes: 5600,
	}
	for name, testCase := range map[string]struct {
		omitted []OmittedFile
		problem string
	}{
		"a listed fixture":                {omitted: []OmittedFile{listed}},
		"a fixture the change deletes":    {omitted: []OmittedFile{deleted}},
		"source the bound cut":            {omitted: []OmittedFile{{Path: "internal/readmodel/throughput.go", Bytes: 13216, Reason: OmittedPatchFull, Class: FileClassSource}}, problem: "is source and the patch does not show it"},
		"a test the bound cut":            {omitted: []OmittedFile{{Path: "internal/readmodel/throughput_test.go", Bytes: 15189, Reason: OmittedPatchFull, Class: FileClassTest}}, problem: "is test and the patch does not show it"},
		"a fixture with nothing to open":  {omitted: []OmittedFile{{Path: "internal/dashboard/testdata/link.html", Reason: OmittedUnreadable, Class: FileClassFixture}}, problem: "does not list whole"},
		"a fixture the listing cannot id": {omitted: []OmittedFile{{Path: "internal/dashboard/testdata/renders/stale.html", Bytes: 22126, Reason: OmittedPatchFull, Class: FileClassFixture}}, problem: "does not list whole"},
	} {
		problems := ChangeDiff{Truncated: true, OmittedFiles: testCase.omitted}.UnreviewableOmissions()
		switch {
		case testCase.problem == "" && len(problems) > 0:
			t.Errorf("%s: unreviewable = %#v, want an omission a review can be completed over", name, problems)
		case testCase.problem != "" && len(problems) != 1:
			t.Errorf("%s: unreviewable = %#v, want the one omission named", name, problems)
		case testCase.problem != "" && !strings.Contains(problems[0], testCase.problem):
			t.Errorf("%s: unreviewable = %q, want it to say %q", name, problems[0], testCase.problem)
		}
	}
}

// dashboardPageDiffShape is yoyodyne-ifd.141.3's diff against its recorded
// base, d2f8d6a0244ffa176193e82a22807e5170e0fe3c, as the byte size of each
// file's own diff: `git diff <base> <tip> -- <path> | wc -c` for every path in
// the change, read from the branch at its tip 2a24a7dc178713d4148da156b8b043895f5fb2b5.
var dashboardPageDiffShape = map[string]int{
	"docs/developing-yoyo.md":                                         2763,
	"docs/operations.md":                                              11875,
	"internal/backlog/backlog.go":                                     4235,
	"internal/backlog/backlog_test.go":                                1812,
	"internal/cli/dashboard.go":                                       5928,
	"internal/cli/dashboard_test.go":                                  1921,
	"internal/dashboard/assets/dashboard.css":                         19094,
	"internal/dashboard/assets/dashboard.js":                          42507,
	"internal/dashboard/assets/shell.html":                            6626,
	"internal/dashboard/fixtureserver/main.go":                        4892,
	"internal/dashboard/fixtureserver/main_test.go":                   1576,
	"internal/dashboard/page_test.go":                                 16391,
	"internal/dashboard/server.go":                                    4273,
	"internal/dashboard/server_test.go":                               2410,
	"internal/dashboard/testdata/fixtures/standing-busy.json":         7130,
	"internal/dashboard/testdata/fixtures/standing-degraded.json":     2784,
	"internal/dashboard/testdata/fixtures/standing-held.json":         4710,
	"internal/dashboard/testdata/fixtures/standing-quiet.json":        624,
	"internal/dashboard/testdata/fixtures/standing-unreadable.json":   1335,
	"internal/dashboard/testdata/fixtures/throughput-busy.json":       1635,
	"internal/dashboard/testdata/fixtures/throughput-degraded.json":   1142,
	"internal/dashboard/testdata/fixtures/throughput-quiet.json":      1047,
	"internal/dashboard/testdata/fixtures/throughput-unreadable.json": 1236,
	"internal/dashboard/testdata/render.js":                           16221,
	"internal/dashboard/testdata/renders/busy.html":                   21873,
	"internal/dashboard/testdata/renders/degraded.html":               14469,
	"internal/dashboard/testdata/renders/held.html":                   18310,
	"internal/dashboard/testdata/renders/loading.html":                1266,
	"internal/dashboard/testdata/renders/matrix.json":                 3176,
	"internal/dashboard/testdata/renders/quiet.html":                  4146,
	"internal/dashboard/testdata/renders/refused.html":                1533,
	"internal/dashboard/testdata/renders/signin.html":                 1773,
	"internal/dashboard/testdata/renders/stale.html":                  22126,
	"internal/dashboard/testdata/renders/throughput-pending.html":     19154,
	"internal/dashboard/testdata/renders/throughput-refused.html":     19325,
	"internal/dashboard/testdata/renders/throughput-stale.html":       22189,
	"internal/dashboard/testdata/renders/unreachable.html":            1564,
	"internal/dashboard/testdata/renders/unreadable.html":             5845,
	"internal/dashboard/testdata/renders/wrong-token.html":            1848,
	"internal/readmodel/standing.go":                                  9139,
	"internal/readmodel/standing_test.go":                             8195,
	"internal/readmodel/throughput.go":                                13216,
	"internal/readmodel/throughput_test.go":                           15189,
}

// assertPatchOrder holds a patch to presenting the named files in the order
// given, each of them present.
func assertPatchOrder(t *testing.T, patch string, order []string) {
	t.Helper()
	last := -1
	for _, path := range order {
		offset := strings.Index(patch, "diff --git a/"+path+" b/"+path)
		if offset < 0 {
			t.Errorf("%s is not in the patch:\n%s", path, patch)
			continue
		}
		if offset < last {
			t.Errorf("%s is presented ahead of the file that should precede it:\n%s", path, patch)
		}
		last = offset
	}
}

// sectionFor is one file's own block of a patch, header included.
func sectionFor(t *testing.T, patch, path string) string {
	t.Helper()
	for _, section := range splitPatchSections(patch) {
		if strings.HasPrefix(section, "diff --git a/"+path+" b/"+path+"\n") {
			return section
		}
	}
	t.Fatalf("%s is not in the patch:\n%s", path, patch)
	return ""
}

// numberedLines is n distinct lines of about forty bytes each, so a removal of
// some of them is a diff Git renders as removals alone rather than as a rewrite.
func numberedLines(prefix string, from, to int) string {
	var lines strings.Builder
	for index := from; index < to; index++ {
		fmt.Fprintf(&lines, "%s line %06d of the document, padded\n", prefix, index)
	}
	return lines.String()
}

// A file the change deletes whole is described at the base commit rather than
// rendered as the removal of all of it, and a file reduced by removal alone is
// described the same way where it does not fit in what every other file left of
// the bound — and shown whole where it does. yoyodyne-ifd.117.4 cut
// docs/configuration.md by 378,605 bytes, the removal diff outgrew the
// 262,144-byte bound, and the omission of a document refused the approval
// however sound the reduction was. A file rewritten in part is not a removal and
// is still bounded, and omitted, exactly as before.
func TestARemovalIsDescribedAtItsBaseRatherThanOmitted(t *testing.T) {
	t.Parallel()

	repository := newRepository(t)
	lines := DefaultMaxDiffBytes/40 + 1000
	deleted := numberedLines("deleted", 0, lines)
	reduced := numberedLines("reduced", 0, lines)
	rewritten := numberedLines("rewritten", 0, lines)
	small := numberedLines("small", 0, 10)
	for path, content := range map[string]string{
		"docs/deleted.md": deleted, "docs/reduced.md": reduced, "docs/rewritten.md": rewritten, "docs/small.md": small,
	} {
		writeFile(t, repository, path, content)
	}
	runGit(t, repository, "add", "--all")
	runGit(t, repository, "commit", "-m", "the documents")
	manager := newManager(t, repository, filepath.Join(t.TempDir(), "worktrees"))
	worktree, err := manager.Create(context.Background(), CreateRequest{RunID: testRunID, WorkItemID: "yoyodyne-ifd.429.7", BaseRef: "HEAD"})
	if err != nil {
		t.Fatalf("Create() error = %v", err)
	}
	if err := os.Remove(filepath.Join(worktree.Path, "docs", "deleted.md")); err != nil {
		t.Fatalf("Remove() error = %v", err)
	}
	left := numberedLines("reduced", 0, 500)
	writeFile(t, worktree.Path, "docs/reduced.md", left)
	writeFile(t, worktree.Path, "docs/rewritten.md", numberedLines("rewrote", 0, lines))
	writeFile(t, worktree.Path, "docs/small.md", numberedLines("small", 0, 9))

	changes, err := manager.UnifiedChanges(context.Background(), worktree, DiffLimits{})
	if err != nil {
		t.Fatalf("UnifiedChanges() error = %v", err)
	}
	base := worktree.BaseCommit
	byPath := map[string]DeletedFile{}
	for _, file := range changes.DeletedFiles {
		byPath[file.Path] = file
	}
	if len(byPath) != 2 {
		t.Fatalf("deleted files = %#v, want the deletion and the large reduction", changes.DeletedFiles)
	}
	whole := byPath["docs/deleted.md"]
	if !whole.Whole || whole.BaseCommit != base || whole.BaseBytes != int64(len(deleted)) ||
		whole.BaseDigest != "git-blob:"+gitLine(t, repository, "rev-parse", base+":docs/deleted.md") ||
		whole.Bytes != 0 || whole.Digest != "" || whole.RemovedLines != lines {
		t.Errorf("deleted whole = %#v, want its size and blob at the base and nothing at the tip", whole)
	}
	described := whole.Describe()
	for _, want := range []string{"docs/deleted.md", "deleted whole", fmt.Sprintf("%d bytes at base commit %s", len(deleted), base), "`git show " + base + ":docs/deleted.md`", whole.BaseDigest} {
		if !strings.Contains(described, want) {
			t.Errorf("described deletion = %q, want %q in it", described, want)
		}
	}
	reduction := byPath["docs/reduced.md"]
	if reduction.Whole || reduction.BaseBytes != int64(len(reduced)) || reduction.Bytes != int64(len(left)) ||
		reduction.Digest != digestOf(left) || reduction.RemovedLines != lines-500 {
		t.Errorf("reduction = %#v, want it described at the base with what is left at the tip", reduction)
	}
	if described := reduction.Describe(); !strings.Contains(described, "reduced by removal alone") || strings.Contains(described, "deleted whole") {
		t.Errorf("described reduction = %q", described)
	}

	// Neither large removal is in the patch or among the omissions; the small
	// reduction fits in what the bound has left, so which line it took is still
	// shown; the rewrite is still bounded.
	for _, path := range []string{"docs/deleted.md", "docs/reduced.md"} {
		if strings.Contains(changes.Patch, "a/"+path) {
			t.Errorf("%s is rendered in the patch", path)
		}
	}
	if section := sectionFor(t, changes.Patch, "docs/small.md"); !strings.Contains(section, "-small line 000009") {
		t.Errorf("the small removal is not shown whole:\n%s", section)
	}
	if len(changes.OmittedFiles) != 1 || changes.OmittedFiles[0].Path != "docs/rewritten.md" {
		t.Fatalf("omitted files = %#v, want the rewrite alone", changes.OmittedFiles)
	}
	problems := changes.UnreviewableOmissions()
	if len(problems) != 1 || !strings.Contains(problems[0], "docs/rewritten.md") {
		t.Errorf("unreviewable = %v, want the rewrite alone", problems)
	}
}

// A branch's accumulated change describes a deletion the same way, at the base
// the branch was grown from.
func TestBranchChangesDescribesADeletionAtItsBase(t *testing.T) {
	t.Parallel()

	repository := newRepository(t)
	content := numberedLines("deleted", 0, DefaultMaxDiffBytes/40+1000)
	writeFile(t, repository, "docs/deleted.md", content)
	runGit(t, repository, "add", "--all")
	runGit(t, repository, "commit", "-m", "the document")
	base := gitLine(t, repository, "rev-parse", "HEAD")
	runGit(t, repository, "checkout", "-b", "accumulated")
	runGit(t, repository, "rm", "-q", "docs/deleted.md")
	runGit(t, repository, "commit", "-m", "delete the document")
	runGit(t, repository, "checkout", "main")
	manager := newManager(t, repository, filepath.Join(t.TempDir(), "worktrees"))

	change, err := manager.BranchChanges(context.Background(), BranchRequest{Branch: "accumulated", BaseRef: "main"}, DiffLimits{})
	if err != nil {
		t.Fatalf("BranchChanges() error = %v", err)
	}
	if change.Changes.Truncated || len(change.Changes.OmittedFiles) != 0 || change.Changes.Patch != "" {
		t.Fatalf("the deletion was rendered or omitted: truncated=%t omitted=%#v", change.Changes.Truncated, change.Changes.OmittedFiles)
	}
	if len(change.Changes.DeletedFiles) != 1 {
		t.Fatalf("deleted files = %#v, want the document", change.Changes.DeletedFiles)
	}
	deleted := change.Changes.DeletedFiles[0]
	if !deleted.Whole || deleted.BaseCommit != base || deleted.BaseBytes != int64(len(content)) ||
		deleted.BaseDigest != "git-blob:"+gitLine(t, repository, "rev-parse", base+":docs/deleted.md") {
		t.Errorf("deleted = %#v, want it described at the branch's base", deleted)
	}
}

// Only a diff of removed lines is a removal: an added line, a creation, a type
// change, a mode change, and a binary change to a file that remains are not.
func TestRemovalOnlyReadsTheDiff(t *testing.T) {
	t.Parallel()

	for name, test := range map[string]struct {
		patch   string
		whole   bool
		removed int
		ok      bool
	}{
		"deleted whole":      {"diff --git a/x b/x\ndeleted file mode 100644\nindex 1..0\n--- a/x\n+++ /dev/null\n@@ -1,2 +0,0 @@\n-one\n-two\n", true, 2, true},
		"deleted binary":     {"diff --git a/x b/x\ndeleted file mode 100644\nindex 1..0\nBinary files a/x and /dev/null differ\n", true, 0, true},
		"reduced":            {"diff --git a/x b/x\nindex 1..2 100644\n--- a/x\n+++ b/x\n@@ -1,3 +1,1 @@\n keep\n-one\n-two\n", false, 2, true},
		"removed patch text": {"diff --git a/x b/x\nindex 1..2 100644\n--- a/x\n+++ b/x\n@@ -1,2 +1,1 @@\n keep\n-diff --git a/y b/y\n", false, 1, true},
		"rewritten":          {"diff --git a/x b/x\nindex 1..2 100644\n--- a/x\n+++ b/x\n@@ -1,2 +1,2 @@\n-one\n+uno\n", false, 0, false},
		"created":            {"diff --git a/x b/x\nnew file mode 100644\nindex 0..1\n--- /dev/null\n+++ b/x\n@@ -0,0 +1 @@\n+one\n", false, 0, false},
		"type change":        {"diff --git a/x b/x\ndeleted file mode 100644\n--- a/x\n+++ /dev/null\n@@ -1 +0,0 @@\n-one\ndiff --git a/x b/x\nnew file mode 120000\n--- /dev/null\n+++ b/x\n@@ -0,0 +1 @@\n+target\n", false, 0, false},
		"mode change":        {"diff --git a/x b/x\nold mode 100644\nnew mode 100755\n", false, 0, false},
		"binary changed":     {"diff --git a/x b/x\nindex 1..2 100644\nBinary files a/x and b/x differ\n", false, 0, false},
	} {
		whole, removed, ok := removalOnly(test.patch)
		if whole != test.whole || removed != test.removed || ok != test.ok {
			t.Errorf("%s: removalOnly() = %t, %d, %t, want %t, %d, %t", name, whole, removed, ok, test.whole, test.removed, test.ok)
		}
	}
}

// A reduction that would fit in the bound displaces nothing from it. Rendered in
// its place in the order, a reduction of most of the bound is placed ahead of a
// source file that sorts after it, and that file is then kept out and refuses
// the approval: the failure the rule exists to remove, reached by a reduction
// that fits rather than one that does not. Placed after every other file, it is
// spent only against what they leave, and here it is described.
func TestARemovalThatFitsSpendsNoneOfTheBound(t *testing.T) {
	t.Parallel()

	repository := newRepository(t)
	lines := DefaultMaxDiffBytes * 3 / 4 / 40
	reduced := numberedLines("reduced", 0, lines+10)
	writeFile(t, repository, "docs/a-reduced.md", reduced)
	runGit(t, repository, "add", "--all")
	runGit(t, repository, "commit", "-m", "the document")
	manager := newManager(t, repository, filepath.Join(t.TempDir(), "worktrees"))
	worktree, err := manager.Create(context.Background(), CreateRequest{RunID: testRunID, WorkItemID: "yoyodyne-ifd.429.7", BaseRef: "HEAD"})
	if err != nil {
		t.Fatalf("Create() error = %v", err)
	}
	writeFile(t, worktree.Path, "docs/a-reduced.md", numberedLines("reduced", 0, 10))
	code := numberedLines("// code", 0, DefaultMaxDiffBytes/2/40)
	writeFile(t, worktree.Path, "internal/z/code.go", code)
	worktree.HarnessCommit = harnessCommit(t, worktree.Path, "yoyodyne: reduce the document and add the code")

	changes, err := manager.UnifiedChanges(context.Background(), worktree, DiffLimits{})
	if err != nil {
		t.Fatalf("UnifiedChanges() error = %v", err)
	}
	if len(changes.DeletedFiles) != 1 || changes.DeletedFiles[0].Path != "docs/a-reduced.md" || changes.DeletedFiles[0].RemovedLines != lines {
		t.Fatalf("deleted files = %#v, want the reduction described", changes.DeletedFiles)
	}
	if changes.Truncated || len(changes.OmittedFiles) != 0 {
		t.Fatalf("the reduction spent the bound: omitted = %#v", changes.OmittedFiles)
	}
	sectionFor(t, changes.Patch, "internal/z/code.go")
	if problems := changes.UnreviewableOmissions(); len(problems) != 0 {
		t.Errorf("unreviewable = %v", problems)
	}

	// The branch's accumulated change follows the same rule.
	branch := gitLine(t, worktree.Path, "rev-parse", "--abbrev-ref", "HEAD")
	accumulated, err := manager.BranchChanges(context.Background(), BranchRequest{Branch: branch, BaseRef: "main"}, DiffLimits{})
	if err != nil {
		t.Fatalf("BranchChanges() error = %v", err)
	}
	if len(accumulated.Changes.DeletedFiles) != 1 || accumulated.Changes.Truncated || len(accumulated.Changes.OmittedFiles) != 0 {
		t.Fatalf("branch: deleted = %#v, omitted = %#v, want the reduction described and nothing omitted",
			accumulated.Changes.DeletedFiles, accumulated.Changes.OmittedFiles)
	}
	sectionFor(t, accumulated.Changes.Patch, "internal/z/code.go")
}
