package gitworktree

import (
	"context"
	"path/filepath"
	"strings"
	"testing"
)

// The class a path is given decides where the patch presents it, so the rules
// are held to by name: Go's own conventions first, then the ones the projects
// here have actually shipped.
func TestClassifyPathReadsTheConventions(t *testing.T) {
	t.Parallel()

	for path, want := range map[string]FileClass{
		"internal/readmodel/throughput.go":                     FileClassSource,
		"docs/operations.md":                                   FileClassSource,
		"internal/dashboard/assets/dashboard.js":               FileClassSource,
		"cmd/yoyo/main.go":                                     FileClassSource,
		"internal/readmodel/throughput_test.go":                FileClassTest,
		"internal/dashboard/page_test.go":                      FileClassTest,
		"web/app.test.js":                                      FileClassTest,
		"web/app.spec.ts":                                      FileClassTest,
		"test/integration/smoke.go":                            FileClassTest,
		"internal/dashboard/testdata/renders/busy.html":        FileClassFixture,
		"internal/dashboard/testdata/render.js":                FileClassFixture,
		"internal/orchestrator/testdata/baseline/a-run.json":   FileClassFixture,
		"web/__snapshots__/app.test.js.snap":                   FileClassFixture,
		"spec/fixtures/users.yml":                              FileClassFixture,
		"internal/cli/golden/status.txt":                       FileClassFixture,
		"internal/cli/status.golden":                           FileClassFixture,
		"go.sum":                                               FileClassFixture,
		"web/package-lock.json":                                FileClassFixture,
		"internal/api/service.pb.go":                           FileClassFixture,
		"internal/api/zz_generated.deepcopy.go":                FileClassFixture,
		"internal/schema/types_gen.go":                         FileClassFixture,
		"internal/dashboard/testdata/fixtures/standing.json":   FileClassFixture,
		"internal/gitworktree/testdata/a_test.go":              FileClassFixture,
		"internal/gitworktree/presentation_test.go":            FileClassTest,
		"internal/backend/conformance/adapters_test.go":        FileClassTest,
		"internal/backend/conformance/suite.go":                FileClassSource,
		"docs/diagnoses/yoyodyne-ifd-238-probe-crosstalk.md":   FileClassSource,
		"internal/dashboard/testdata/renders/wrong-token.html": FileClassFixture,
	} {
		if got := ClassifyPath(path); got != want {
			t.Errorf("ClassifyPath(%q) = %q, want %q", path, got, want)
		}
	}
}

// A generated file announces itself in its own first line and nowhere in its
// path, so the marker in its rendered diff is what classes it — and only for a
// file the path calls source, since the path has already settled the others.
func TestClassifySectionReadsTheGeneratedMarker(t *testing.T) {
	t.Parallel()

	generated := "diff --git a/internal/api/types.go b/internal/api/types.go\n+// Code generated by protoc-gen-go. DO NOT EDIT.\n+package api\n"
	if got := classifySection("internal/api/types.go", generated); got != FileClassFixture {
		t.Errorf("a file carrying Go's generated marker classed as %q, want a fixture", got)
	}
	context := "diff --git a/internal/api/types.go b/internal/api/types.go\n // Code generated by mockery v2. DO NOT EDIT.\n+func added() {}\n"
	if got := classifySection("internal/api/types.go", context); got != FileClassFixture {
		t.Errorf("a modified generated file classed as %q, want a fixture", got)
	}
	shell := "diff --git a/scripts/env.sh b/scripts/env.sh\n+# Code generated by make env. DO NOT EDIT.\n"
	if got := classifySection("scripts/env.sh", shell); got != FileClassFixture {
		t.Errorf("a generated shell file classed as %q, want a fixture", got)
	}
	// The sentence quoted inside a source file's body is not the marker: the
	// marker is a whole line, and a diff line carrying prose about it is not one.
	prose := "diff --git a/internal/gitworktree/manager.go b/internal/gitworktree/manager.go\n+\t// A generated file carries `// Code generated ... DO NOT EDIT.` at its head.\n"
	if got := classifySection("internal/gitworktree/manager.go", prose); got != FileClassSource {
		t.Errorf("prose about the marker classed the file as %q, want source", got)
	}
	// A line removed from the file is the file's past, not its present.
	removed := "diff --git a/internal/api/types.go b/internal/api/types.go\n-// Code generated by protoc-gen-go. DO NOT EDIT.\n+package api\n"
	if got := classifySection("internal/api/types.go", removed); got != FileClassSource {
		t.Errorf("a removed marker classed the file as %q, want source", got)
	}
}

// The bound is spent source first, then tests, then test data, across the
// committed and uncommitted halves of a worktree together, so a change whose
// fixtures sort ahead of its code presents the code whole and lets the bound
// fall on the fixtures. Git lists both halves alphabetically, which is the order
// that sent yoyodyne-ifd.141.3's read model to review unseen.
func TestManagerUnifiedChangesPresentsSourceThenTestsThenFixtures(t *testing.T) {
	t.Parallel()

	repository := newRepository(t)
	manager := newManager(t, repository, filepath.Join(t.TempDir(), "worktrees"))
	worktree, err := manager.Create(context.Background(), CreateRequest{RunID: testRunID, WorkItemID: "yoyodyne-order", BaseRef: "HEAD"})
	if err != nil {
		t.Fatalf("Create() error = %v", err)
	}
	// Alphabetically the renders come first and the read model last, and the
	// generated file sorts among the source. One source file and one test are
	// committed by an earlier attempt; the others are this round's worktree.
	writeFile(t, worktree.Path, "internal/dashboard/testdata/renders/busy.html", strings.Repeat("<li>a rendered row</li>\n", 10))
	writeFile(t, worktree.Path, "internal/dashboard/testdata/renders/quiet.html", strings.Repeat("<li>a quiet row</li>\n", 10))
	writeFile(t, worktree.Path, "internal/readmodel/standing.go", "package readmodel\n\nfunc Standing() {}\n")
	writeFile(t, worktree.Path, "internal/readmodel/standing_test.go", "package readmodel\n\nfunc TestStanding() {}\n")
	worktree.HarnessCommit = harnessCommit(t, worktree.Path, "yoyodyne: published attempt")
	writeFile(t, worktree.Path, "internal/api/types.go", "// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage api\n")
	writeFile(t, worktree.Path, "internal/readmodel/throughput.go", "package readmodel\n\nfunc Throughput() {}\n")
	writeFile(t, worktree.Path, "internal/readmodel/throughput_test.go", "package readmodel\n\nfunc TestThroughput() {}\n")

	whole, err := manager.UnifiedChanges(context.Background(), worktree, DiffLimits{})
	if err != nil {
		t.Fatalf("UnifiedChanges() error = %v", err)
	}
	if whole.Truncated {
		t.Fatalf("an unbounded change was reported as cut: %#v", whole.OmittedFiles)
	}
	order := []string{
		"internal/readmodel/standing.go",
		"internal/readmodel/throughput.go",
		"internal/readmodel/standing_test.go",
		"internal/readmodel/throughput_test.go",
		"internal/api/types.go",
		"internal/dashboard/testdata/renders/busy.html",
		"internal/dashboard/testdata/renders/quiet.html",
	}
	assertPatchOrder(t, whole.Patch, order)
	// The listing says what each file is, in the order Git gave it: the listing
	// is the inventory and the patch is the presentation.
	classes := map[string]FileClass{}
	for _, file := range whole.Files {
		classes[file.Path] = file.Class
	}
	for path, want := range map[string]FileClass{
		"internal/readmodel/throughput.go":              FileClassSource,
		"internal/readmodel/throughput_test.go":         FileClassTest,
		"internal/dashboard/testdata/renders/busy.html": FileClassFixture,
	} {
		if classes[path] != want {
			t.Errorf("listing classes %s as %q, want %q", path, classes[path], want)
		}
	}
	if described := (ChangedFile{Path: "internal/dashboard/testdata/renders/busy.html", Status: "A", Bytes: 240, Class: FileClassFixture}).Describe(); !strings.Contains(described, "test data or generated") {
		t.Errorf("a listed fixture is not said to be one: %q", described)
	}

	// A bound that holds the source and the tests and not the renders. The
	// generated file is a fixture too, so it is behind the tests whatever its
	// path sorts as, and the bound falls on it and on the renders.
	sourceAndTests := 0
	for _, path := range order[:4] {
		sourceAndTests += len(sectionFor(t, whole.Patch, path))
	}
	bounded, err := manager.UnifiedChanges(context.Background(), worktree, DiffLimits{MaxTotalBytes: sourceAndTests + 40})
	if err != nil {
		t.Fatalf("UnifiedChanges() bounded error = %v", err)
	}
	if !bounded.Truncated {
		t.Fatalf("a bounded change was reported as complete: %#v", bounded)
	}
	assertPatchOrder(t, bounded.Patch, order[:4])
	for _, kept := range order[:4] {
		if !strings.Contains(bounded.Patch, "diff --git a/"+kept+" b/"+kept) {
			t.Errorf("a file ahead of the bound is missing from the patch: %s\n%s", kept, bounded.Patch)
		}
	}
	for _, dropped := range order[4:] {
		if strings.Contains(bounded.Patch, dropped) {
			t.Errorf("a fixture behind the bound is in the patch: %s", dropped)
		}
	}
	// What was cut is the tail of the order, named in that order, and each one
	// says it is a fixture — a reviewer told the patch is missing test data
	// reads the omission differently from one told it is missing code.
	if len(bounded.OmittedFiles) != 3 {
		t.Fatalf("omitted files = %#v, want the three fixtures", bounded.OmittedFiles)
	}
	for index, dropped := range order[4:] {
		omitted := bounded.OmittedFiles[index]
		if omitted.Path != dropped || omitted.Class != FileClassFixture || omitted.Reason != OmittedPatchFull {
			t.Errorf("omission %d = %#v, want %s named as a fixture the bound had no room for", index, omitted, dropped)
		}
		if described := omitted.Describe(); !strings.Contains(described, "test data or generated") || !strings.Contains(described, dropped) {
			t.Errorf("described omission = %q, want the path and its class", described)
		}
	}
	// A source omission is described without a class: code is what a reviewer
	// assumes an omission is, and saying so would say nothing.
	if described := (OmittedFile{Path: "big.go", Bytes: 10, Reason: OmittedPatchFull, Class: FileClassSource, Bound: 5}).Describe(); strings.Contains(described, "source") {
		t.Errorf("a source omission names its class: %q", described)
	}
}

// The accumulated change on a branch is presented in the same order, for the
// same reason: the reviewer must not have to care which of the two it was
// handed.
func TestBranchChangesPresentsSourceThenTestsThenFixtures(t *testing.T) {
	t.Parallel()

	repository := newRepository(t)
	accumulate(t, repository, "accumulated",
		[2]string{"internal/dashboard/testdata/renders/busy.html", strings.Repeat("<li>a rendered row</li>\n", 10)},
		[2]string{"internal/readmodel/throughput.go", "package readmodel\n\nfunc Throughput() {}\n"},
		[2]string{"internal/readmodel/throughput_test.go", "package readmodel\n\nfunc TestThroughput() {}\n"},
	)
	manager := newManager(t, repository, filepath.Join(t.TempDir(), "worktrees"))

	whole, err := manager.BranchChanges(context.Background(), BranchRequest{Branch: "accumulated", BaseRef: "main"}, DiffLimits{})
	if err != nil {
		t.Fatalf("BranchChanges() error = %v", err)
	}
	order := []string{"internal/readmodel/throughput.go", "internal/readmodel/throughput_test.go", "internal/dashboard/testdata/renders/busy.html"}
	assertPatchOrder(t, whole.Changes.Patch, order)

	codeBytes := len(sectionFor(t, whole.Changes.Patch, order[0])) + len(sectionFor(t, whole.Changes.Patch, order[1]))
	bounded, err := manager.BranchChanges(context.Background(), BranchRequest{Branch: "accumulated", BaseRef: "main"}, DiffLimits{MaxTotalBytes: codeBytes + 40})
	if err != nil {
		t.Fatalf("BranchChanges() bounded error = %v", err)
	}
	assertPatchOrder(t, bounded.Changes.Patch, order[:2])
	if strings.Contains(bounded.Changes.Patch, "busy.html") {
		t.Errorf("the fixture behind the bound is in the patch:\n%s", bounded.Changes.Patch)
	}
	if len(bounded.Changes.OmittedFiles) != 1 || bounded.Changes.OmittedFiles[0].Path != order[2] ||
		bounded.Changes.OmittedFiles[0].Class != FileClassFixture || bounded.Changes.OmittedFiles[0].Reason != OmittedPatchFull {
		t.Fatalf("omitted files = %#v, want the render named as a fixture the bound had no room for", bounded.Changes.OmittedFiles)
	}
}

// yoyodyne-ifd.141.3's change replayed through the default bound: the shape of
// its diff against its base — every path, with the size of that path's diff —
// is what went to review, 368,503 bytes against a 262,144-byte bound. Spent
// alphabetically, the bound was gone before internal/readmodel was reached and
// the read model went to review unseen; spent in class order, the read model
// and every other source and test file is presented whole and what the bound
// keeps out is renders.
func TestTheDashboardPageChangeReplayedThroughTheBoundPresentsTheReadModelWhole(t *testing.T) {
	t.Parallel()

	repository := newRepository(t)
	manager := newManager(t, repository, filepath.Join(t.TempDir(), "worktrees"))
	worktree, err := manager.Create(context.Background(), CreateRequest{RunID: testRunID, WorkItemID: "yoyodyne-ifd.141.3", BaseRef: "HEAD"})
	if err != nil {
		t.Fatalf("Create() error = %v", err)
	}
	// Each file is written at the byte size of its diff in the real change, as
	// lines, so the rendered diff here is that size plus a header and a `+` a
	// line: within a few percent of what the reviewer was handed.
	for path, bytes := range dashboardPageDiffShape {
		lines := bytes / 40
		writeFile(t, worktree.Path, path, strings.Repeat(strings.Repeat("x", 39)+"\n", lines))
	}
	worktree.HarnessCommit = harnessCommit(t, worktree.Path, "yoyodyne: yoyodyne-ifd.141.3 Dashboard 3 of 3")

	changes, err := manager.UnifiedChanges(context.Background(), worktree, DiffLimits{})
	if err != nil {
		t.Fatalf("UnifiedChanges() error = %v", err)
	}
	if !changes.Truncated {
		t.Fatalf("a change of %d bytes against a %d-byte bound was reported as complete", len(changes.Patch), DefaultMaxDiffBytes)
	}
	if len(changes.Patch) > DefaultMaxDiffBytes {
		t.Fatalf("patch is %d bytes, want at most %d", len(changes.Patch), DefaultMaxDiffBytes)
	}
	for path := range dashboardPageDiffShape {
		class := ClassifyPath(path)
		shown := strings.Contains(changes.Patch, "diff --git a/"+path+" b/"+path)
		if class != FileClassFixture && !shown {
			t.Errorf("%s (%s) is not in the patch; the bound cut code ahead of the fixtures", path, class)
		}
	}
	for _, omitted := range changes.OmittedFiles {
		if omitted.Class != FileClassFixture || !strings.HasPrefix(omitted.Path, "internal/dashboard/testdata/") {
			t.Errorf("the bound kept out %s (%s); only renders and fixtures may be behind it", omitted.Path, omitted.Class)
		}
	}
	if len(changes.OmittedFiles) == 0 {
		t.Fatal("nothing was kept out of a change larger than the bound")
	}
	// The read model in particular — the throughput derivation the page depends
	// on, which is what the reviewer said she had not seen — is whole.
	for _, path := range []string{
		"internal/readmodel/standing.go", "internal/readmodel/throughput.go",
		"internal/readmodel/standing_test.go", "internal/readmodel/throughput_test.go",
	} {
		section := sectionFor(t, changes.Patch, path)
		line := "+" + strings.Repeat("x", 39) + "\n"
		if want := dashboardPageDiffShape[path] / 40; strings.Count(section, line) != want {
			t.Errorf("%s is shown with %d of its %d lines", path, strings.Count(section, line), want)
		}
	}

	// And the change is one a reviewer can approve. Ordering the bound put the
	// code in front of her; this is the other half of it — every omission is a
	// fixture, and every one of those is listed with the size and the digest that
	// make it openable, so nothing about the representation refuses the approval.
	// Without it the change is reviewable and unclosable, which is what
	// yoyodyne-ifd.404 left behind and what yoyodyne-ifd.425 is for.
	if problems := changes.UnreviewableOmissions(); len(problems) > 0 {
		t.Errorf("the change cannot be approved: %s", strings.Join(problems, "; "))
	}
	for _, omitted := range changes.OmittedFiles {
		if !strings.HasPrefix(omitted.Digest, "sha256:") || !omitted.ListedWhole() {
			t.Errorf("omission = %#v, want it delivered as evidence somebody can open and check", omitted)
		}
	}
}

// The narrowed refusal, at the grain the rule is written in: an omission is one
// a review can be completed over only where it is test data and the listing says
// which bytes were kept out.
func TestUnreviewableOmissionsNamesWhatAnApprovalCannotCover(t *testing.T) {
	t.Parallel()

	listed := OmittedFile{
		Path: "internal/dashboard/testdata/renders/busy.html", Bytes: 21873, Reason: OmittedPatchFull,
		Class: FileClassFixture, Bound: 262144, Digest: "sha256:" + strings.Repeat("a", 64),
	}
	deleted := OmittedFile{
		Path: "internal/dashboard/testdata/renders/gone.html", Bytes: 0, Reason: OmittedPatchFull,
		Class: FileClassFixture, Bound: 262144, DiffBytes: 5600,
	}
	for name, testCase := range map[string]struct {
		omitted []OmittedFile
		problem string
	}{
		"a listed fixture":                {omitted: []OmittedFile{listed}},
		"a fixture the change deletes":    {omitted: []OmittedFile{deleted}},
		"source the bound cut":            {omitted: []OmittedFile{{Path: "internal/readmodel/throughput.go", Bytes: 13216, Reason: OmittedPatchFull, Class: FileClassSource}}, problem: "is source and the patch does not show it"},
		"a test the bound cut":            {omitted: []OmittedFile{{Path: "internal/readmodel/throughput_test.go", Bytes: 15189, Reason: OmittedPatchFull, Class: FileClassTest}}, problem: "is test and the patch does not show it"},
		"a fixture with nothing to open":  {omitted: []OmittedFile{{Path: "internal/dashboard/testdata/link.html", Reason: OmittedUnreadable, Class: FileClassFixture}}, problem: "does not list whole"},
		"a fixture the listing cannot id": {omitted: []OmittedFile{{Path: "internal/dashboard/testdata/renders/stale.html", Bytes: 22126, Reason: OmittedPatchFull, Class: FileClassFixture}}, problem: "does not list whole"},
	} {
		problems := ChangeDiff{Truncated: true, OmittedFiles: testCase.omitted}.UnreviewableOmissions()
		switch {
		case testCase.problem == "" && len(problems) > 0:
			t.Errorf("%s: unreviewable = %#v, want an omission a review can be completed over", name, problems)
		case testCase.problem != "" && len(problems) != 1:
			t.Errorf("%s: unreviewable = %#v, want the one omission named", name, problems)
		case testCase.problem != "" && !strings.Contains(problems[0], testCase.problem):
			t.Errorf("%s: unreviewable = %q, want it to say %q", name, problems[0], testCase.problem)
		}
	}
}

// dashboardPageDiffShape is yoyodyne-ifd.141.3's diff against its recorded
// base, d2f8d6a0244ffa176193e82a22807e5170e0fe3c, as the byte size of each
// file's own diff: `git diff <base> <tip> -- <path> | wc -c` for every path in
// the change, read from the branch at its tip 2a24a7dc178713d4148da156b8b043895f5fb2b5.
var dashboardPageDiffShape = map[string]int{
	"docs/developing-yoyo.md":                                         2763,
	"docs/operations.md":                                              11875,
	"internal/backlog/backlog.go":                                     4235,
	"internal/backlog/backlog_test.go":                                1812,
	"internal/cli/dashboard.go":                                       5928,
	"internal/cli/dashboard_test.go":                                  1921,
	"internal/dashboard/assets/dashboard.css":                         19094,
	"internal/dashboard/assets/dashboard.js":                          42507,
	"internal/dashboard/assets/shell.html":                            6626,
	"internal/dashboard/fixtureserver/main.go":                        4892,
	"internal/dashboard/fixtureserver/main_test.go":                   1576,
	"internal/dashboard/page_test.go":                                 16391,
	"internal/dashboard/server.go":                                    4273,
	"internal/dashboard/server_test.go":                               2410,
	"internal/dashboard/testdata/fixtures/standing-busy.json":         7130,
	"internal/dashboard/testdata/fixtures/standing-degraded.json":     2784,
	"internal/dashboard/testdata/fixtures/standing-held.json":         4710,
	"internal/dashboard/testdata/fixtures/standing-quiet.json":        624,
	"internal/dashboard/testdata/fixtures/standing-unreadable.json":   1335,
	"internal/dashboard/testdata/fixtures/throughput-busy.json":       1635,
	"internal/dashboard/testdata/fixtures/throughput-degraded.json":   1142,
	"internal/dashboard/testdata/fixtures/throughput-quiet.json":      1047,
	"internal/dashboard/testdata/fixtures/throughput-unreadable.json": 1236,
	"internal/dashboard/testdata/render.js":                           16221,
	"internal/dashboard/testdata/renders/busy.html":                   21873,
	"internal/dashboard/testdata/renders/degraded.html":               14469,
	"internal/dashboard/testdata/renders/held.html":                   18310,
	"internal/dashboard/testdata/renders/loading.html":                1266,
	"internal/dashboard/testdata/renders/matrix.json":                 3176,
	"internal/dashboard/testdata/renders/quiet.html":                  4146,
	"internal/dashboard/testdata/renders/refused.html":                1533,
	"internal/dashboard/testdata/renders/signin.html":                 1773,
	"internal/dashboard/testdata/renders/stale.html":                  22126,
	"internal/dashboard/testdata/renders/throughput-pending.html":     19154,
	"internal/dashboard/testdata/renders/throughput-refused.html":     19325,
	"internal/dashboard/testdata/renders/throughput-stale.html":       22189,
	"internal/dashboard/testdata/renders/unreachable.html":            1564,
	"internal/dashboard/testdata/renders/unreadable.html":             5845,
	"internal/dashboard/testdata/renders/wrong-token.html":            1848,
	"internal/readmodel/standing.go":                                  9139,
	"internal/readmodel/standing_test.go":                             8195,
	"internal/readmodel/throughput.go":                                13216,
	"internal/readmodel/throughput_test.go":                           15189,
}

// assertPatchOrder holds a patch to presenting the named files in the order
// given, each of them present.
func assertPatchOrder(t *testing.T, patch string, order []string) {
	t.Helper()
	last := -1
	for _, path := range order {
		offset := strings.Index(patch, "diff --git a/"+path+" b/"+path)
		if offset < 0 {
			t.Errorf("%s is not in the patch:\n%s", path, patch)
			continue
		}
		if offset < last {
			t.Errorf("%s is presented ahead of the file that should precede it:\n%s", path, patch)
		}
		last = offset
	}
}

// sectionFor is one file's own block of a patch, header included.
func sectionFor(t *testing.T, patch, path string) string {
	t.Helper()
	for _, section := range splitPatchSections(patch) {
		if strings.HasPrefix(section, "diff --git a/"+path+" b/"+path+"\n") {
			return section
		}
	}
	t.Fatalf("%s is not in the patch:\n%s", path, patch)
	return ""
}
