package config

// The baseline a materialized configuration keeps beside it, and the values a
// bundle supplies that it is a record of.
//
// A project generated by `yoyo init` states every value explicitly and inherits
// nothing, which is what makes the file it can read the whole of what runs. The
// price is that a later executable improving a persona or a selector reaches
// nothing: a two-way diff against a freshly regenerated file cannot tell a value
// the operator deliberately changed from one the bundle improved, and reports
// both as differences.
//
// The baseline is the missing third side. It records what the bundle supplied at
// the moment the project materialized, so the comparison in drift.go is three-way
// rather than a diff.
//
// **Nothing in the load path reads it.** That is the property the whole record
// rests on and the one a later change is most likely to take away: what the
// configuration file says is still exactly what runs, and this file decides
// nothing about that. It is generated, it is committed beside the configuration
// so a collaborator's checkout compares the same way this one does, and a project
// that has none simply cannot be compared.

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"sort"
	"strings"

	"go.yaml.in/yaml/v3"
)

const (
	// LockFileName is the baseline, inside DirectoryName beside the
	// configuration it is the baseline of.
	LockFileName = "config.lock"
	// LockVersion versions this record apart from the configuration schema. A
	// baseline written by an older executable is read rather than refused where
	// it can be, and the two numbers move for different reasons.
	LockVersion = 1
)

// Lock is what a bundle supplied when a project materialized from it.
type Lock struct {
	// Version is LockVersion, so a baseline this executable cannot read says so
	// rather than being compared as if it were empty.
	Version int `yaml:"version" json:"version"`
	// Bundle names the template the values came from.
	Bundle string `yaml:"bundle" json:"bundle"`
	// Revision digests the values below as one thing. Comparing it against the
	// bundle in the running executable answers "has anything moved at all"
	// without walking every key, which is the answer for almost every run.
	Revision string `yaml:"revision" json:"revision"`
	// Values is each value as that bundle supplied it, keyed the way
	// `config show --origins` keys them so an operator reading a notice and an
	// operator reading the origins are reading one vocabulary.
	Values map[string]string `yaml:"values" json:"values"`
}

// BaselineRevisionPrefix marks a baseline revision as one, the way
// RevisionPrefix marks a configuration revision. They are different digests over
// different things and a reader who mistook one for the other would compare two
// numbers that were never going to agree.
const BaselineRevisionPrefix = "bnd-"

// NewLock records what a bundle supplies, as the baseline of a project
// materializing from it.
func NewLock(bundleName string) (Lock, error) {
	values, err := BundleValues(bundleName)
	if err != nil {
		return Lock{}, err
	}
	return Lock{
		Version:  LockVersion,
		Bundle:   bundleName,
		Revision: baselineRevision(values),
		Values:   values,
	}, nil
}

// BundleValues is every value a bundle supplies, keyed by the origin vocabulary.
//
// It is derived by resolving the bundle on its own and keeping the keys the
// bundle itself was recorded as the origin of, rather than by reading the
// bundle document: a value the bundle states and a value it leaves to a harness
// default are different things, and only the first is something a later bundle
// can improve. The same pass is what excludes the derived values -- an agent's
// capabilities, its account, the repair grant -- which no layer supplies and
// which would otherwise look like bundle content that moved.
func BundleValues(bundleName string) (map[string]string, error) {
	template, err := loadBuiltinBundle(bundleName)
	if err != nil {
		return nil, err
	}
	resolved, err := resolveLayers([]layer{{
		origin:   template.name,
		document: template.document,
		personas: template.personas,
	}})
	if err != nil {
		return nil, err
	}

	flattened := flattenConfig(resolved.Config)
	values := make(map[string]string, len(resolved.Origins))
	for key, origin := range resolved.Origins {
		if origin != template.name || !inheritableFromBundle(key) {
			continue
		}
		// A supplied key with no value of its own is a subtree rather than a
		// setting: `agents.<name>.persona` is recorded as one origin and
		// serializes as several fields. It is skipped here and compared below by
		// the one thing about it worth comparing, which is what it says.
		if value, present := flattened[key]; present {
			values[key] = value
		}
	}
	// A persona is the value most worth telling a project about and the one the
	// flattened configuration says least about: its text is deliberately out of
	// the serialized form, so what survives is a path and a byte count. Each one
	// the bundle supplied is recorded as a digest of what it actually says.
	for name, agent := range resolved.Config.Agents {
		if resolved.Origins["agents."+name+".persona"] != template.name || !agent.Persona.Defined() {
			continue
		}
		values[personaTextKey(name)] = personaTextDigest(agent.Persona.Text)
	}
	return values, nil
}

// personaTextKey names an agent's persona text as a key of its own, beside the
// path and version the flattened configuration already carries. It is not a key
// any configuration document has, and it is not one `--origins` reports: it
// names a value rather than a setting, which is why it reads as `.text` rather
// than as something an operator could write.
func personaTextKey(agent string) string { return "agents." + agent + ".persona.text" }

// personaTextDigest is how a persona's text is compared. The text itself is not
// recorded: a baseline is committed beside the configuration, and a copy of
// every persona in it would be a second copy of files that are already in the
// project, drifting from them.
func personaTextDigest(text string) string {
	sum := sha256.Sum256([]byte(text))
	return "text-" + hex.EncodeToString(sum[:])[:RevisionDigits]
}

// inheritableFromBundle reports whether a key is one a project could take from a
// bundle at all. Two are not, for the reasons checkBundleDocument refuses them:
// a version taken from a bundle would let a file written against another schema
// load as whatever the bundle said, and `extends` is the statement of
// inheritance rather than something inherited. A baseline carrying either would
// report an "improvement" no project could ever adopt.
func inheritableFromBundle(key string) bool {
	return key != "version" && key != "extends"
}

// baselineRevision digests a baseline's values as one thing, so two baselines
// can be compared without walking either.
func baselineRevision(values map[string]string) string {
	digest := sha256.New()
	for _, key := range sortedKeys(values) {
		digest.Write([]byte(key))
		digest.Write([]byte{0})
		digest.Write([]byte(values[key]))
		digest.Write([]byte{0})
	}
	return BaselineRevisionPrefix + hex.EncodeToString(digest.Sum(nil))[:RevisionDigits]
}

// Render writes the baseline as the file that is committed, headed by what it is
// for and by the one thing a reader has to know about it: nothing loads it.
//
// The revision it writes is digested from the values it is writing rather than
// taken from the field, so the file it produces is always one DecodeLock will
// read back. A record that could be written already disagreeing with itself
// would fail as an edit somebody made.
func (l Lock) Render() []byte {
	l.Revision = baselineRevision(l.Values)
	var builder strings.Builder
	fmt.Fprintf(&builder, `# Yoyodyne configuration baseline -- generated, and not read when the
# configuration loads.
#
# It records what the %s template supplied when this project materialized its
# configuration, which is the third side of a comparison that would otherwise be
# a diff: with it, "yoyo config drift" can tell a value you changed from one the
# template improved. What config.yaml says is still exactly what runs.
#
# Commit it beside the configuration. Editing it by hand only makes the
# comparison lie; regenerate it with "yoyo init --force" instead.
version: %d
bundle: %s
revision: %s
values:
`, l.Bundle, l.Version, l.Bundle, l.Revision)
	for _, key := range sortedKeys(l.Values) {
		encoded, _ := json.Marshal(l.Values[key])
		fmt.Fprintf(&builder, "  %s: %s\n", key, encoded)
	}
	return []byte(builder.String())
}

// DecodeLock reads a baseline. Unknown keys are refused the way the
// configuration decoder refuses them: a baseline this executable half
// understands would compare against half a record.
func DecodeLock(reader io.Reader) (Lock, error) {
	decoder := yaml.NewDecoder(reader)
	decoder.KnownFields(true)
	var lock Lock
	if err := decoder.Decode(&lock); err != nil {
		return Lock{}, fmt.Errorf("decode %s: %w", LockFileName, err)
	}
	if lock.Version != LockVersion {
		return Lock{}, fmt.Errorf("decode %s: baseline declares version %d, and this executable reads version %d",
			LockFileName, lock.Version, LockVersion)
	}
	if strings.TrimSpace(lock.Bundle) == "" {
		return Lock{}, fmt.Errorf("decode %s: baseline names no bundle", LockFileName)
	}
	// A baseline whose revision does not digest its own values is one somebody
	// edited, and a record of where values came from that somebody has since
	// rewritten is not a record. It is refused here rather than compared: an
	// answer computed from it would be confidently wrong, which is the one thing
	// worse than having no baseline at all.
	if recomputed := baselineRevision(lock.Values); recomputed != lock.Revision {
		return Lock{}, fmt.Errorf("decode %s: the baseline says %s and its values digest to %s, so it has been edited since it was written; "+
			"regenerate it with `yoyo init --force`", LockFileName, lock.Revision, recomputed)
	}
	return lock, nil
}

// flattenConfig renders an effective configuration as one value per key, keyed
// the way origins are keyed.
//
// It goes through the configuration's own JSON form rather than a second
// description of the same struct, so a field added to the configuration is a key
// here without anybody remembering to add it -- and a field the configuration
// deliberately keeps out of that form, a persona's text, stays out here too and
// is recorded separately above.
func flattenConfig(cfg Config) map[string]string {
	encoded, err := json.Marshal(cfg)
	if err != nil {
		return map[string]string{}
	}
	var tree any
	if err := json.Unmarshal(encoded, &tree); err != nil {
		return map[string]string{}
	}
	values := map[string]string{}
	flattenValue("", tree, values)
	return values
}

// flattenValue walks the decoded configuration into dotted keys. A list is one
// value rather than a key per element: every list in a configuration -- the
// checks, the research sources, the work-item exemptions -- is replaced as a
// whole rather than merged, so half a list is not a thing any layer said.
//
// A string is kept as itself rather than in its JSON form, because these values
// are printed back to an operator: a model selector reported as `"opus"` inside
// a second pair of quotes is a value nobody wrote.
func flattenValue(prefix string, value any, into map[string]string) {
	switch typed := value.(type) {
	case map[string]any:
		for _, key := range sortedAnyKeys(typed) {
			child := key
			if prefix != "" {
				child = prefix + "." + key
			}
			flattenValue(child, typed[key], into)
		}
	case string:
		into[prefix] = typed
	default:
		encoded, _ := json.Marshal(typed)
		into[prefix] = string(encoded)
	}
}

func sortedAnyKeys(values map[string]any) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func sortedKeys(values map[string]string) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}
